### ISSUE TITLE
Export module

### ISSUE THREAD

**Issue by ThomasAtome** [tleunen/pixi-multistyle-text#12]
Hi,

I encountered some problems during installation of your module.

We used pixi as a dependency in our project, so not like in your demo in a simple html file.

So we have to export your class for make a require in the other files were we need to use MultiStyleText.

Is this normal ? Did i do something wrong ?

Thanks :)

**Comment by bluepichu** [comment]
How are you building your project?  (e.g., ES6 module imports with something like Webpack or Rollup, or via TypeScript?)

There is a missing `export` at the moment that I'm trying to fix - it has some issues with the way that TS emits the declaration files.

**Comment by ThomasAtome** [comment]
We used ES5 with webpack.

`module.exports = MultiStyleText;`

Just adding this at the end of the js script file resolved my problem.

**Comment by bluepichu** [comment]
This is mostly fixed by just adding Webpack to our build chain (see 77648e7).  However, this does cause a breaking change: the class is now accessed via `MultiStyleText.MultiStyleText` since it's behind a "module".

Also, the fix above is only marked as partial because the `.d.ts` file is still helplessly broken (but somewhat more so than it was before).  The built `pixi-multistyle-text.js` in that commit should suffice if you're not using TS.

**Comment by bluepichu** [comment]
(Pardon the history rewrite; the commit message was blatantly wrong.  See fb261ca.)

**Comment by ThomasAtome** [comment]
Thanks for the commit :)

I have another problem now, when i try to launch my npm test, the test crashed and said me that "PIXI is not defined". Do you have any idea ?

**Comment by tleunen** [comment]
@bluepichu Where are your commits? I don't see any PR with the fixes to be merged

**Comment by bluepichu** [comment]
There isn't a PR yet - I still need to fix something related to the emitted `.d.ts`.  The work thus far is on [the `iss12` branch of my fork](https://github.com/bluepichu/pixi-multistyle-text/tree/iss12).
