### ISSUE TITLE
Blurred text on retina display

### ISSUE THREAD

**Issue by Izaias** [tleunen/pixi-multistyle-text#4]
Hi Tommy

I love pixi-multistyle-text! Very well done!

But after testing it on hi-res displays (iPad retina and a modern Android phone) I noticed that the text looks blurry. So I decided to try and fix it. The solution is rather simple, though.

Just change the value of this.resolution (which apparently is aways 1) to window.devicePixelRatio || 1;

I couldn't find out where you set this.resolution in your code, so I just overwrote it

from:
```javascript
this.texture.baseTexture.resolution = this.resolution;
```

to:
```javascript
this.resolution = window.devicePixelRatio || 1;
this.texture.baseTexture.resolution = this.resolution;
```

I hope this helps. Keep up the good work!

**Comment by tleunen** [comment]
Hey @Izaias,

Thanks! Unfortunately, I'm not an active user of the lib anymore.
At the time I did it, Pixi didn't have anything for retina display. Now I think it does support it.

Anyway, this module probably needs a full revamp to be a real module that you could use with the new Pixi 3. I can try to find some time to update it, otherwise any help are welcome! :)

**Comment by Izaias** [comment]
Thanks @tleunen! I'm definitely interested in helping - although I'm still a quite newbie. I'll study a bit more and see what I can come up with. Stay tuned.
