### ISSUE TITLE
Vertical alignment

### ISSUE THREAD

**Issue by GregoryBabonaux** [tleunen/pixi-multistyle-text#41]
Hey ! 

Got a little problem with the alignment of the text : 

<img width="215" alt="capture d ecran 2017-02-07 15 50 55" src="https://cloud.githubusercontent.com/assets/500614/22696153/5a6b20ec-ed4d-11e6-9d4d-0ac336e1c332.png">

The first canvas is provided by FabricJS and the iText object

The second canvas is a PIXI canvas

As you can see, with a valign set to bottom, there's an offset between the first letter (H) and the rest f the word (ello)

I don't see any options to remove this offset (i tried with differents valign)

Any way to fix this ?

**Comment by bluepichu** [comment]
That definitely makes sense to add.  Right now we only have `top`, `middle`, and `bottom` as values for `valign`, which clearly doesn't cover any case.

Any thoughts on how we could rework this property?  It seems like it might be good to mimic `vertical-align` from CSS, which would give us these values:

- `baseline` - the baseline of this text is aligned with the baseline of surrounding text
- `sub` - the baseline of this text is aligned with the subscript line of surrounding text
- `super` - the baseline of this text is aligned with the superscript line of surrounding text
- `middle` - same as the `middle` we already have, I think
- `text-top` - like the `top` we have now; I'd probably keep it as `top` for backwards-compatibility
- `text-bottom` - like the `bottom` we have now; I'd probably keep it as `bottom` for backwards-compatibility
- `<number>` - the baseline of this text is the given length (in our case, the value in pixels) above the surrounding text's baseline

With these values, @GregoryBabonaux would be looking for either `baseline` or `0`, which also seems like a reasonable default.

**Comment by bluepichu** [comment]
e6d3303 adds `baseline` as a potential option to valign:

<img width="306" alt="screenshot 2017-02-09 15 14 32" src="https://cloud.githubusercontent.com/assets/1878074/22801458/dc8576ac-eeda-11e6-9c1d-5184793933b2.png">

@GregoryBabonaux, if you need a version of this library that has this feature right now, you can build your own copy from this commit:

```
git clone https://github.com/bluepichu/pixi-multistyle-text.git
cd pixi-multistyle-text
git checkout iss41
npm install
npm run demo
```

I'm going to leave this open for the time being rather than make the PR so I can consider the other options and what the default should be (probably `baseline`, at the unfortunate cost of a breaking change).

**Comment by GregoryBabonaux** [comment]
Great thanks @bluepichu ! 

I'll try this today

**Comment by bluepichu** [comment]
Hmmm... `sub` and `super` aren't well-defined for `vertical-align` in CSS (it's basically just "somewhere appropriate").  `sub` also affects the line-height, which is interesting and hard to account for.  (If a whole line of text is `sub`, where is that line positioned?  Below where the baseline would normally be?)

For now I'll stick with `"top" | "middle" | "baseline" | "bottom" | number`, since that should cover the common cases.

**Comment by bluepichu** [comment]
I have this mostly working now, but ran into an issue with what the definition of `"middle"` is.  In the current implementation, it aligns the vertical center of the text to the vertical center of the line.  This makes sense when the positions are restricted to top, middle, and bottom, but given the ability to offset by an arbitrary amount, where is the middle?  I see three obvious options here:

1. Align to the center of the resulting line height.  This may require some special-casing in the event that all of the text on a line is valign middle.
2. Align to the center of the line height if we assume that all text on the line is aligned to the baseline.  This works out identically to the current logic if custom offsets are never used.
3. Align to the center of the parent text.  This mirrors the CSS spec for `vertical-align: middle`.  (Then we'd also need to consider what the "center of the parent text" is - the CSS answer would be to align to the center of lower-case letters in the parent text.)

**Comment by bluepichu** [comment]
I think 3 is the best option and is doable, but I know I don't have time to do it now, so I've gone ahead with option 1 and will create a new issue to fix the `middle` implementation.

**Comment by bluepichu** [comment]
Defered valign middle to #50.

PR filed: #51.
