### ISSUE TITLE
Throws error when line is empty

### ISSUE THREAD

**Issue by hendrysadrak** [tleunen/pixi-multistyle-text#42]
Link to jsfiddle: https://jsfiddle.net/190geq9c/

When using text where one line is empty (i.e. when text contains \n\n) it will throw an error.

![image](https://cloud.githubusercontent.com/assets/4000963/24398967/e901be56-13b3-11e7-9e05-25fd49e2d0c8.png)

**Comment by hendrysadrak** [comment]
The quickfix i found for now is not having empty lines but atleast have one space on the line (i.e. \n \n)

**Comment by bluepichu** [comment]
Thanks for the report.  It looks like this occurs because of lines 223-225 of #40, which was put there to prevent adding character spacing for characters that don't exist.  This caused the font properties to not be computed, so they were left as `undefined`.

The fix should be merged in shortly, but is in [the `iss-42` branch of my fork](https://github.com/bluepichu/pixi-multistyle-text/tree/iss42) if you need it now.

**Comment by bluepichu** [comment]
PR filed: #43.

**Comment by hendrysadrak** [comment]
Super! Thank you for your quick response! I'm soon using this lib in production 😄
