### ISSUE TITLE
Deprecation warnings in PIXI 4.5.0

### ISSUE THREAD

**Issue by hendrysadrak** [tleunen/pixi-multistyle-text#44]
This throws deprecation warnings when used with pixi 4.5.

![image](https://cloud.githubusercontent.com/assets/4000963/25331187/bd534bc0-28ea-11e7-8d8a-f38be3bb13e0.png)

I can help out with PR.

**Comment by bluepichu** [comment]
Feel free to file one, or I'll handle it in a couple hours when I'm free.

**Comment by bluepichu** [comment]
The fixes are pretty easy and are implemented - [see the `iss44` branch on my fork](https://github.com/bluepichu/pixi-multistyle-text/tree/iss44) - but we're stuck waiting on `@types/pixi.js` to resync with `pixi-typescript` to get the typings for 4.5.0, as otherwise TypeScript will complain when you try to build.  In the meantime, I've checked in a built copy on [the `iss44-built` branch on my fork](https://github.com/bluepichu/pixi-multistyle-text/tree/iss44-built), so you should be able to use the built files there in the meantime.

We probably also need to consider the versioning implications of this change, since it'll break support for all Pixi versions pre-4.5.0.

**Comment by bluepichu** [comment]
PR filed, to be merged in once `@types/pixi.js` gets 4.5.0 and once we figure out what to do about versioning: #45.
